language: generic
os: linux
services: docker
branches:
  only:
  - master
env:
  global:
  - PROJECT_NAME=lpp-metrics
  - PROJECT_VERSION=1.0.3
  - DOCKER_USERNAME=bezpov
  - secure: H/tIjqESD/uMkdTTc3Ite4QeoPh7379flyIPbXi7O6n4daEbJRYOy/dDoLyPRyctTk06F0bB3aVdu7ZGmXb/FYfen0uUYeHQWE2rX0eFfClf0Rik0sKh7INv7JrEXmLwaP2M6B41cjwOWOOrXP3AWaD/cWgdhaFPfHWYcGOeniuWXNTGDcmwqdNtWycDgUupM8Q75so052oscAVVn6lW4VqhDTu8A+m1aW6poEVIspElR4UbWTyAXuE6rZQGSXMGb+X3O1q4DqINLgGzH3OzHPnMf2dqHLtDs8Z7P67q3y9pXy8wCx5JcOQPVvNNMK97492fRglDLwjUo1D2VFYbTeimrNzFHn4GvmbETbb87J7cO9d0dR4Eyvmt/kMB1ro8howwP2WeSATnhddvV92y7sIvWtGtXYYhy6sDMlEwvpsEz06rCU4IZyLwlvi+JLDt9N/NITHlmPPAfD071Cr9WEvnUkfMy+NTA0SzO3ZbyG0gu48CVE5ubgwhsbB1HmQTQ7cee7Eib72LFexN6+hnI6XFSh9Hc0qaulwZ5GXmqSLqbxYl8mc1amZtCUaCLjPh6uP6REsF41Z63KWHuT2QdBgbO84x5W4yW+E1RIBv5P20kOUzqgaGRS6vimoMSv8jBZzOWH0TQwdcouhtqpP2ow7Vr/2tbblCN5mJaDEep5o=
  - secure: PpOoY+6S3SVr+yrT7V1bpTJKP0dl2OnBgtwZVAUTqg3U6GXh+eCHiW1qZJLHnYwsUiiQCtGyyxB+lGKB98d37O204KHMl6tkwGFDZ1bvD1lvEcnqqqFTL/UoSPmt3B1sVOlIwUZUJysTWQ4O/TElRb18n4xZhQZMEmvpEXAE6NEm8sdneChnQ5oGTEVjgXOQ1YYM+A/56FBosxl2TnviZrhsz81Rl5vSW4WXsY3/j6H1IBQickUe+EywbcfplBEyxBKPJ105EPAGoIoTB5UoIJQFnqpvsShBPuyiIQm3iE49fzFIYmZ3qxZ6ltcnzeU+GwNadhSqMYPFF7mUS7CkOQOaTh0vB6ZzjFltaejb01k6UmeqUurhFMZikNOIn2yf5SDq4P4rJktwQoCZ+Gqq1L/f1Ro8jY50vvhikDIdgXaX5XhkmXdmNbH352a4W9e0e8B5Y4BiD4Po1V4Jbw/I9OIZ5VsIFjkAjXK7A6oIB/5uHFS2kSSasfrDQJcCFpXTs9ld20BKjkkxgV6VjTXO5KUcVUfW4+R66w5PNHwyzh+k1H6lBF0/Kae+DmuCREZaHLPYeJr6cf2F/s6o5S8wUyn4egR4d5lKmD3P8FNT/kBS75MftmSlNQXKMtpo3OtYySKF7LxFBN/kyofLHB76s+seSDGiy6iEWaOT59GPziw=
before_install:
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ./config/google-travis-service-account.json.gpg
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file ./config/google-travis-service-account.json
- gcloud config set project massive-boulder-263710
- gcloud container clusters get-credentials lpp --zone us-central1-a --project massive-boulder-263710
- gcloud components install kubectl
- kubectl apply -f ./kubernetes/deployment.yaml
